name: Tracking issue
description: File a bug report.
title: "[DATE]: [FEATURE NAME]"
labels: ["bug", "triage"]
assignees: octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: title
    attributes:
      label: Title
      description: A clear and concise title of what the bug is.
      placeholder: Bug title
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true
