name: Build Images

on:
  push:
    branches: master
  pull_request:
      paths:
        - docker-compose.yml
        - services

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        profile: [automatic, comfy, download]
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.profile }}
            type=ref,event=pr,suffix=-${{ matrix.profile }}
            type=semver,pattern={{version}},suffix=-${{ matrix.profile }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.profile }}
            type=raw,value=${{ matrix.profile }},enable={{is_default_branch}}
            type=raw,value=latest-${{ matrix.profile }},enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.profile }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.profile }}
