name: Build Images

on:
  push:
    branches: master
  pull_request:
      paths:
        - docker-compose.yml
        - services

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        profile: [automatic, comfy, download]
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compose dockers
        run: docker compose --profile ${{ matrix.profile }} build --progress plain
